### ISSUE TITLE
Config file not found

### ISSUE THREAD

**Issue by tpsteiner** [mar-mei/guide2go#34]
**Describe the bug**
I can't seem to get this to work. When I run docker compose up, the docker status is "Restarting" and the docker logs show "config file not found". Other people had a similar problem:
https://forum.openmediavault.org/index.php?thread/47315-is-there-a-docker-to-grab-schedules-direct-epg-data/
https://ubuntuforums.org/showthread.php?t=2485826

**To Reproduce**
New debian 12 LXC with sudo user
Install go docker curl
add docker-compose.yml to home dir
```yaml
services:
    guide2go:
      container_name: g2g
      image: chuchodavids/guide2go:stable
      ports:
        - 8080:8080
      environment:
        - TZ=America/Denver
      volumes:
        - ./data/config/guide2go:/config
        - ./data/livetv/:/data/livetv/
        - ./data/images:/data/images/
      restart: always
```

Note that some edits were made, "./" in front of folders, "=" instead of colon next to TZ. I think these were mistakes in the guidance?

```bash
sudo docker compose up -d
```

```bash
sudo docker compose logs g2g

2024/04/28 03:15:36 [G2G  ] Version: 1.1.3
2024/04/28 03:15:36 config file not found
```

At this point I have not yet built the guide2go program with go.

Earlier I did build the program and created a config file, but I'm not sure where to even put it. What config file is it looking for, and where is the it looking? Any guidance is appreciated.
